#include <INCVIDEO.H>

WORD VIDEO_tabskip_default[] =
                 {VIDEO_MTTECLA(VD_NULO ,SOBE),
                  VIDEO_MTTECLA(VD_NULO ,DESCE),
                  VIDEO_MTTECLA(VD_NULO ,DIREITA),
                  VIDEO_MTTECLA(VD_NULO ,ESQUERDA),
                  VIDEO_MTTECLA(VD_NULO ,CTRL_DIR),
                  VIDEO_MTTECLA(VD_NULO ,CTRL_ESQ),
                  VIDEO_MTTECLA(VD_NULO ,TABSCAN),
                  VIDEO_MTTECLA(VD_TAB  ,TABSCAN),
                  VIDEO_MTTECLA(VD_NULO ,HOME),
                  VIDEO_MTTECLA(VD_NULO ,END),
                  VIDEO_MTTECLA(VD_NULO ,PGUP),
                  VIDEO_MTTECLA(VD_NULO ,PGDN),
                  VIDEO_MTTECLA(VD_NULO ,CTRL_PGUP),
                  VIDEO_MTTECLA(VD_NULO ,CTRL_PGDN),
                  VIDEO_MTTECLA(VD_NULO ,CTRL_HOME),
                  VIDEO_MTTECLA(VD_NULO ,CTRL_END),
                  VIDEO_MTTECLA(VD_NULO ,SHIFT_PGDN),
                  VIDEO_MTTECLA(VD_NULO ,SHIFT_PGUP),
                  VIDEO_MTTECLA(ENTER   ,ENTERSCAN),
                  VIDEO_MTTECLA(CTRL_ENT,ENTERSCAN),
                  VIDEO_MTTECLA(VD_NULO ,ESCAPESCAN),
                  VIDEO_MTTECLA(ESCAPE  ,ESCAPESCAN),
                  VIDEO_MTTECLA(ESCAPE  ,ESCAPE    ),
                  VIDEO_MTTECLA(VD_NULO ,ALT_S),
                  VIDEO_MTTECLA(VD_NULO ,ALT_O),
                  VIDEO_MTTECLA(VD_NULO ,ALT_E),
                  VIDEO_MTTECLA(VD_NULO ,ALT_I),
                  VIDEO_MTTECLA(VD_NULO ,ALT_MENOS),
                  VIDEO_MTTECLA(VD_NULO ,ALT_MAIS),
                  VIDEO_MTTECLA(VD_NULO ,ALT_P),
                  VIDEO_MTTECLA(VD_NULO ,ALT_C),
                  VIDEO_MTTECLA(VD_NULO ,ALT_B),
                  VIDEO_MTTECLA(VD_NULO,ALT_M),
                  VIDEO_MTTECLA(VD_NULO,ALT_F),
                  VIDEO_MTTECLA(VD_NULO,ALT_R),
/*
                  VIDEO_MTTECLA(VD_NULO,ALT_1),
                  VIDEO_MTTECLA(VD_NULO,ALT_2),
                  VIDEO_MTTECLA(VD_NULO,ALT_3),
                  VIDEO_MTTECLA(VD_NULO,ALT_4),
                  VIDEO_MTTECLA(VD_NULO,ALT_5),
                  VIDEO_MTTECLA(VD_NULO,ALT_6),
                  VIDEO_MTTECLA(VD_NULO,ALT_7),
                  VIDEO_MTTECLA(VD_NULO,ALT_8),
                  VIDEO_MTTECLA(VD_NULO,ALT_9),
                  VIDEO_MTTECLA(VD_NULO,ALT_0),
*/
                  VIDEO_MTTECLA(VD_NULO,ALT_A),
                  VIDEO_MTTECLA(VD_NULO,ALT_L),
                  VIDEO_MTTECLA(VD_NULO,104),
                  VIDEO_MTTECLA(VD_NULO,F1),
                  VIDEO_MTTECLA(VD_NULO,F2),
                  VIDEO_MTTECLA(VD_NULO,F10),
                  VIDEO_MTTECLA(VD_NULO,F9),
                  VIDEO_MTTECLA(VD_NULO,F8),
                  VIDEO_MTTECLA(VD_NULO,F7),
                  VIDEO_MTTECLA(VD_NULO,F6),
                  VIDEO_MTTECLA(VD_NULO,F5),
                  VIDEO_MTTECLA(VD_NULO,F4),
                  VIDEO_MTTECLA(VD_NULO,F3),

                  VD_MTTECLA(VD_NULO,ALT_F2 ) ,
                  VD_MTTECLA(VD_NULO,ALT_F3 ) ,
                  VD_MTTECLA(VD_NULO,ALT_F4 ) ,
                  VD_MTTECLA(VD_NULO,ALT_F5 ) ,
                  VD_MTTECLA(VD_NULO,ALT_F6 ) ,
                  VD_MTTECLA(VD_NULO,ALT_F7 ) ,
                  VD_MTTECLA(VD_NULO,ALT_F8 ) ,
                  VD_MTTECLA(VD_NULO,ALT_F9 ) ,

                  VD_MTTECLA(VD_NULO,CTRL_F1 ) ,
                  VD_MTTECLA(VD_NULO,CTRL_F2 ) ,
                  VD_MTTECLA(VD_NULO,CTRL_F3 ) ,
                  VD_MTTECLA(VD_NULO,CTRL_F4 ) ,
                  VD_MTTECLA(VD_NULO,CTRL_F5 ) ,
                  VD_MTTECLA(VD_NULO,CTRL_F6 ) ,
                  VD_MTTECLA(VD_NULO,CTRL_F7 ) ,
                  VD_MTTECLA(VD_NULO,CTRL_F8 ) ,
                  VD_MTTECLA(VD_NULO,CTRL_F9 ) ,
                  VD_MTTECLA(VD_NULO,CTRL_F10) ,

                  VIDEO_MTTECLA(ASCII_SPOOL,SCAN_SPOOL),
                  VD_MTTECLA(1,VIDEO_MOUSE_BOTCLICK),
                  VD_MTTECLA(2,VIDEO_MOUSE_BOTCLICK),
                  VD_MTTECLA(1,VIDEO_MOUSE_BOTTRV),
                  VD_MTTECLA(2,VIDEO_MOUSE_BOTTRV),
                  VIDEO_MTTECLA(CTRLBAKSP,BAKSPSCAN),
                  VIDEO_MTTECLA(VD_NULO ,VD_NULO)};

