                                "DISPLAY"   , // DISPLAY GENERICO
                                "FORMATO"   , // FORMATO DA COR

                                "SETCAMPO"  , // ACIONA CAMPO
                                "PROTEGE"   , // PROTEGE CAMPO
                                "DESPROTEGE", // DESPROTEGE CAMPO
                                "MOSTRA"    , // MOSTRA
                                "NAO_MOSTRA", // NAO MOSTRA
                                "TROCA"     , // TROCA
                                "NAO_TROCA" , // NAO TROCA

                                "SERVREC"   , // SERVICO REQUISITADO NO NUCLEO
                                "REPDISP"   , // VARIAVEL DE REDISPLAY
                                "TELA"      , // TELA ATIVA
                                "CAMPOS"    , // CAMPOS ATIVO
                                "COL"       , // COLUNA ATUAL
                                "LIN"       , // LINHA ATUAL
                                "COR"       ,

