#include <INCVIDEO.H>

#define    VIDEO_COMANDO   1
#define    VIDEO_SEPARADOR 2
#define    VIDEO_OPERADOR  3
#define    VIDEO_OPERANDO  4

PROCEDURE [NOME] [PARAMETERS ,[RETORNO] ,,,]
CALL [[FUNCION] [PROCEDURE]] [RETORNO, ...[PARAMTROS]]
WHILE([COMPARACAO])
SHITCH([CAMPO])
CASE [VALOR][STRING][TESTE LOGICO]
IF ([TESTE LOGICO])
DISPLAY [COL,NUMERO,CAMPO], [LIN,NUMERO,CAMPO], [MASCARA], [CAMPO,NUMERO,STRING], [FUNDO,ATRIBUTO,FRENTE,ATRIBUTO]


main()
{
}


INT2 VIDEO_LOGICA_testa_sequencia(sequencia)
char *sequencia;
{
 do
  {


}



SET COLOR
SET BUFFER
SET LIN
SET COL
SET


EXTERN TIPO DODA+OFFSET  NOMECAMPO
ARQUIVO->DRECLEN
ARQUIVO->NAME
DODA->TYPE
DODA->LEN
DODA->
ALLOCMEM(DODA,TAMANHO)

